### ISSUE TITLE
custom op 'func' is unknown

### ISSUE THREAD

**Issue by HadXu** [Lewuathe/mlir-hello#12] opened 2022-05-23 03:03 UTC
xx@xx:~/work/mlir-hello$ ./build/bin/hello-opt ./test/Hello/main.mlir > print.ll
loc("./test/Hello/main.mlir":4:3): error: custom op 'func' is unknown (tried 'builtin.func' as well)
Error can't load file ./test/Hello/main.mlir

**Comment by Lewuathe** [comment] 2022-05-23 23:38
@HadXu Hmm, I could not reproduce the problem. Could you try it with the latest code? I believe the latest `hello-opt` is able to recognize `func` dialect.

**Comment by Lewuathe** [comment] 2022-08-31 00:02
We are now using `func.func` in mlir-hello too. This should be fixed. Please let me know if you encounter the same issue again.
https://github.com/Lewuathe/mlir-hello/blob/main/test/Hello/main.mlir

I'll close this.

**Closed by Lewuathe** 2022-08-31 00:02 UTC
